;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        electric-newline-and-maybe-indent
        end-of-visual-line
        indent-buffer
        kill-region
        markdown-exdent-or-delete
        ns-copy-including-secondary
        nxml-electric-slash
        org-self-insert-command
        scroll-up-line
        sgml-slash
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-newline
        end-of-buffer
        help-for-help
        indent-for-tab-command
        kill-this-buffer
        org-promote-subtree
        ))
