;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        copy-region-as-kill
        electric-newline-and-maybe-indent
        electric-verilog-semi
        electric-verilog-tab
        electric-verilog-tick
        end-of-visual-line
        helm-M-x
        indent-buffer
        kill-region
        markdown-exdent-or-delete
        mips-dedent
        nasm-comment
        ns-copy-including-secondary
        nxml-electric-slash
        org-self-insert-command
        scroll-up-line
        sgml-slash
        smex
        transpose-words
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        abbrev-prefix-mark
        autopair-newline
        c-electric-pound
        end-of-buffer
        help-for-help
        indent-for-tab-command
        kill-this-buffer
        mo-vi-ment-jump-up
        org-promote-subtree
        ))
