
(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'load-path "~/.emacs.d/plugins")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")

(load "customize.el")
(load "ld-mode.el")
(load "llvm-mode.el")
(load "gas-mode.el")

(setq org-src-fontify-natively t)
(setq org-support-shift-select t)
(setq show-paren-style 'mixed)
(setq autosave-default nil)
(setq scroll-step 1)
(setq visible-bell t)
(setq custom-safe-themes t)
(setq custom-file "~/.emacs.d/lisp/customize.el")
(setq ring-bell-function 'ignore)
(setq mac-command-modifier 'meta)
(setq mac-option-modifier 'super)
(setq ns-function-modifier 'hyper)
(setq-default show-trailing-whitespace 1)
(setq-default indent-tabs-mode nil)
(setq js-indent-level 2)
(setq c-default-style "linux")
(setq c-basic-offset 2)
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
(put 'dired-find-alternate-file 'disabled nil)
(setq tex-fontify-script nil)
(setq font-latex-fontify-script nil)
(setq initial-frame-alist '((top . 1) (left . 1) (width . 100) (height . 67)))
(setq initial-buffer-choice t)
(setq js2-highlight-external-variables nil)
(setq js2-include-node-externs t)
(setq js2-strict-missing-semi-warning nil)
(setq lua-indent-level 2)
(setq make-backup-files nil)
(setq nav-width 25)
(setq tab-width 4)
(when (and (equal emacs-version "27.2")
           (eql system-type 'darwin))
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))

(global-auto-revert-mode t)
(delete-selection-mode 1)
(column-number-mode 1)
(scroll-bar-mode -1)
(mac-auto-operator-composition-mode 1)
(display-time-mode 1)
(show-paren-mode 1)
(tool-bar-mode -1)

(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(selectrum-mode +1)
(require 'company)
(global-company-mode 1)
(projectile-global-mode 1)
(smartparens-global-mode 1)
(mo-vi-ment-mode 1)
(setq js2-highlight-level 3)
(dumb-jump-mode 1)

(require 'diminish)
(diminish 'ivy-mode)
(diminish 'mo-vi-ment-mode)
(diminish 'smartparens-mode)
(diminish 'projectile-mode "Pr")
(diminish 'company-mode)
(diminish 'eldoc-mode)
(diminish 'irony-mode)
(diminish 'abbrev-mode)
(diminish 'projectile-mode)
(diminish 'dumb-jump-mode)

(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'flycheck-mode)
(add-hook 'c++-mode-hook 'flycheck-mode)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
(add-hook 'irony-mode-hook #'irony-eldoc)
(add-hook 'xref-backend-functions #'dumb-jump-xref-activate)
(add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)
(add-hook 'LaTeX-mode-hook (lambda () (electric-indent-local-mode -1)))
(add-hook 'LaTeX-mode-hook (lambda () (visual-line-mode 1)))

(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.golsp\\'" . python-mode))
(add-to-list 'auto-mode-alist '("\\.ci\\'" . c-mode))
(add-to-list 'auto-mode-alist '("\\.s\\'" . nasm-mode))
(add-to-list 'auto-mode-alist '("\\.asm\\'" . nasm-mode))

;; load these later because they depend on packages
(load "keybindings.el")
(load "defuns.el")

(when (display-graphic-p)
  (load-theme 'habamax t)
  (add-to-list 'default-frame-alist '(font . "IBM Plex Mono 11")))

;; merlin-mode
(let ((opam-share (ignore-errors (car (process-lines "opam" "config" "var" "share")))))
  (when (and opam-share (file-directory-p opam-share))
    ;; Register Merlin
    (add-to-list 'load-path (expand-file-name "emacs/site-lisp" opam-share))
    (autoload 'merlin-mode "merlin" nil t nil)
    ;; Automatically start it in OCaml buffers
    (add-hook 'tuareg-mode-hook 'merlin-mode t)
    (add-hook 'caml-mode-hook 'merlin-mode t)
    ;; Use opam switch to lookup ocamlmerlin binary
    (setq merlin-command 'opam)))
