(global-set-key (kbd "M--") 'scroll-up-line)
(global-set-key (kbd "M-=") 'scroll-down-line)
(global-set-key (kbd "M-s") 'save-buffer)
(global-set-key (kbd "C-c n") 'indent-buffer)
(global-set-key (kbd "s-k") 'kill-current-buffer)
(global-set-key (kbd "s-z") 'undo)
(global-set-key (kbd "s-c") 'copy-region-as-kill)
(global-set-key (kbd "s-x") 'kill-region)
(global-set-key (kbd "s-l") 'goto-line)
(global-set-key (kbd "s-a") 'mark-whole-buffer)
(global-set-key [f5] 'eval-print-last-sexp)
(global-unset-key (kbd "C-x f"))
(global-unset-key (kbd "C-x C-o"))
(global-unset-key (kbd "C-x s"))
(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
(global-set-key (kbd "C-$") 'ace-jump-mode)
(global-set-key (kbd "C-#") 'er/expand-region)
